/** Declaration file generated by dts-gen */

export function Controller(_a: any): any;

export function ErrorMessage({ as: InnerComponent, errors, name, children, }: any): any;

export function FormContext(_a: any): any;

export function useFieldArray({ control, name }: any): any;

export function useForm({ mode = VALIDATION_MODE.onSubmit, reValidateMode = VALIDATION_MODE.onChange, validationSchema, defaultValues = {}, submitFocusError = true, validateCriteriaMode, }: any): any;

export function useFormContext(): any;

